# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [53]:
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [39]:

rg=np.random.default_rng(1) # less than 1
a=rg.random ((2,3,5)) 
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [22]:
x=np.random.random(30)
a=x.reshape (2,3,5)
a

array([[[0.24875863, 0.80470529, 0.91546166, 0.09565086, 0.62352579],
        [0.32506996, 0.70928781, 0.06889411, 0.83236072, 0.58005451],
        [0.19563307, 0.96980968, 0.53365503, 0.37964291, 0.43864952]],

       [[0.34824521, 0.4130565 , 0.40908452, 0.69842609, 0.43543698],
        [0.30559864, 0.87123506, 0.1295013 , 0.69762577, 0.54965953],
        [0.51138928, 0.83648099, 0.98913968, 0.73322124, 0.13650732]]])

In [50]:
a= np.array([[np.random.random(15)],[np.random.random(15)]])
a


array([[[0.18671326, 0.95785426, 0.84955368, 0.84042666, 0.10771091,
         0.441444  , 0.80202094, 0.12471208, 0.64419608, 0.90137182,
         0.96201472, 0.72109101, 0.67739369, 0.74392524, 0.42723433]],

       [[0.79785024, 0.10489871, 0.38450544, 0.41215284, 0.83073907,
         0.56807166, 0.42043589, 0.18054617, 0.30894327, 0.67551694,
         0.3765666 , 0.24122365, 0.76939965, 0.73006776, 0.90201672]]])

#### 4. Print *a*.


In [28]:
a# your code here

array([[[0.9900703 , 0.28215662, 0.93135334, 0.36406703, 0.81383015,
         0.44446117, 0.36039257, 0.63245744, 0.1532089 , 0.5501361 ,
         0.2953141 , 0.68699578, 0.7290735 , 0.95253337, 0.32803186]],

       [[0.02364692, 0.79395364, 0.81602879, 0.67307025, 0.97368442,
         0.86928917, 0.00650686, 0.21708155, 0.66210398, 0.5807239 ,
         0.88515456, 0.01741576, 0.82734259, 0.86033499, 0.02150397]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [29]:
b=np.zeros((5,2,3))
b

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### 6. Print *b*.


In [30]:
b

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [32]:
if a.size==b.size:
    print("equal")
else:
    print ("not equal")

equal


8. Are you able to add *a* and *b*? Why or why not?


In [33]:
c=b+a
not because they have not the same shape

ValueError: operands could not be broadcast together with shapes (5,2,3) (2,1,15) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [36]:
c=b.reshape(2,3,5)
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
d=a+c
d

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
a


array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [42]:
d

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [44]:
e=a*c
e

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [46]:
if e.size==a.size:
    print("equal")
else:
    print("not equal")

equal


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [61]:
d_max=d.max(axis=1)
d_min= d.min(axis=1)
d_mean= d.mean(axis=1)

d_mean

array([[0.56288706, 0.7721032 , 0.29436349, 0.76222395, 0.21419513],
       [0.64288417, 0.3185591 , 0.38839839, 0.44828148, 0.73129865]])

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
f=np.empty((2,3,5))
f


array([[[0.18671326, 0.95785426, 0.84955368, 0.84042666, 0.10771091],
        [0.441444  , 0.80202094, 0.12471208, 0.64419608, 0.90137182],
        [0.96201472, 0.72109101, 0.67739369, 0.74392524, 0.42723433]],

       [[0.79785024, 0.10489871, 0.38450544, 0.41215284, 0.83073907],
        [0.56807166, 0.42043589, 0.18054617, 0.30894327, 0.67551694],
        [0.3765666 , 0.24122365, 0.76939965, 0.73006776, 0.90201672]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [87]:
for x in range(d.shape[0]):
        for y in range(d.shape[1]):
                for z in range(d.shape[2]):
                        if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                                f[x][y][z] = 25
                        elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                                f[x][y][z] = 75
                        elif d[x][y][z] == d_mean:
                                f[x][y][z] = 50
                        elif (d_min) == d[x][y][z]:
                                f[x][y][z] = 0
                        elif (d_max) == d[x][y][z]:
                                f[x][y][z] = 100
print(f)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here